---
- hosts: localhost
  tasks:
    - name: register email
      command: git config --get user.email
      register: email

    - debug:
        var: hostvars['localhost']['email']

- hosts: 'geocircles.cc'
  gather_facts: false
  vars:
    url: 'geocircles.cc'
    name: 'geocircles.cc'
    email: "{{ hostvars['localhost']['email'].stdout  }}"

  tasks:
    - include_vars:
        dir: "group_vars/sites"
      when: hostvars[inventory_hostname]['ansible_user'] is undefined

    - name: 'lookup subdomain ip'
      shell: nslookup {{ url }} | grep Address | tail -1 | awk -F ' ' '{ print $2 }'
      register: target_ip

    - name: Copy nginx conf
      copy:
        src: geocircles.cc.nginx.conf
        dest: /etc/nginx/conf.d/{{ url }}.conf

    - name: Creates directory
      file:
        path: /var/www/html/geocircles.cc
        state: directory

    - name: certify
      become: true
      become_user: root
      shell: "/snap/bin/certbot --nginx -n --agree-tos --email {{ email }} -d {{ url }}"
